import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { FileText, Upload, Shield, Briefcase, Home, Users, FileCheck, Edit3, FileSignature, UploadCloud, List, AlertTriangle, MessageSquare, X, Star } from 'lucide-react';
import { generateEmploymentAgreement, generateRentalAgreement, generateNDA } from '../utils/agreementTemplates';

const Agreements = () => {
    const navigate = useNavigate();
    const [currentStep, setCurrentStep] = useState('landing'); // 'landing' | 'selectType' | 'fillForm' | 'editor'
    const [selectedType, setSelectedType] = useState(null);
    const [reviewSubTab, setReviewSubTab] = useState('upload');
    const [analysisFile, setAnalysisFile] = useState(null);
    const [analysisResult, setAnalysisResult] = useState(null);
    const [isScanning, setIsScanning] = useState(false);
    const [chatMessages, setChatMessages] = useState([]);
    const [chatInput, setChatInput] = useState('');
    const [formData, setFormData] = useState({});
    const [generatedContent, setGeneratedContent] = useState('');

    const fileInputRef = React.useRef(null);

    const agreementTypes = [
        { id: 'nda', title: 'Non-Disclosure Agreement', desc: 'Protect confidential information between parties', icon: Shield, popular: true },
        { id: 'employment', title: 'Employment Contract', desc: 'Formal agreement between employer and employee', icon: Briefcase, popular: true },
        { id: 'rental', title: 'Rental / Lease Agreement', desc: 'Property rental terms compliant with state laws', icon: Home, popular: true },
        { id: 'service', title: 'Service Agreement', desc: 'Terms for professional service delivery', icon: FileText, popular: false },
        { id: 'partnership', title: 'Partnership Deed', desc: 'Define partnership terms and responsibilities', icon: Users, popular: false },
        { id: 'vendor', title: 'Vendor Agreement', desc: 'Contract with suppliers and vendors', icon: FileCheck, popular: false },
        { id: 'freelance', title: 'Freelance Contract', desc: 'Agreement for independent contractors', icon: Edit3, popular: false },
        { id: 'mou', title: 'Memorandum of Understanding', desc: 'Preliminary agreement outlining intentions', icon: FileSignature, popular: false },
    ];

    const handleTypeSelect = (type) => {
        setSelectedType(type);
        setCurrentStep('fillForm');
        // Initialize form data based on type
        if (type.id === 'rental') {
            setFormData({ landlordName: '', tenantName: '', propertyAddress: '', monthlyRent: '', securityDeposit: '', state: '' });
        } else if (type.id === 'employment') {
            setFormData({ employerName: '', employeeName: '', jobTitle: '', monthlySalary: '', startDate: '', workLocation: '' });
        } else if (type.id === 'nda') {
            setFormData({ party1Name: '', party2Name: '', effectiveDate: '', jurisdiction: '' });
        }
    };

    const handleGenerateSubmit = () => {
        let content = '';

        // Generate comprehensive agreement using professional templates
        if (selectedType.id === 'employment') {
            content = generateEmploymentAgreement(formData);
        } else if (selectedType.id === 'rental') {
            content = generateRentalAgreement(formData);
        } else if (selectedType.id === 'nda') {
            content = generateNDA(formData);
        } else {
            // Fallback for other agreement types
            const today = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });
            content = `## ${selectedType.title.toUpperCase()}

This ${selectedType.title} is entered into on **${today}**.

**BETWEEN:** [Party 1 Details]

**AND:** [Party 2 Details]

**[Professional template for ${selectedType.title} is being developed. Please consult a legal professional for comprehensive drafting.]**

**Form Data Collected:**
${JSON.stringify(formData, null, 2)}

---

**Note:** This is a preliminary document. For a legally sound and comprehensive ${selectedType.title}, please engage with a qualified legal professional or advocate.

*Generated by LexMind AI - Advocate Platform*`;
        }

        // Set generated content and show editor
        setGeneratedContent(content);
        setCurrentStep('editor');
    };

    const onUploadClick = () => {
        fileInputRef.current.click();
    };

    const handleFileChange = (e) => {
        const file = e.target.files[0];
        if (!file) return;

        setAnalysisFile(file);
        setIsScanning(true);
        setAnalysisResult(null);
        setChatMessages([]);

        setTimeout(() => {
            setIsScanning(false);
            setAnalysisResult({
                score: 72,
                risks: [
                    { severity: 'High', text: 'Missing Indemnity Clause for Third-Party Claims.' },
                    { severity: 'Medium', text: 'Termination notice period is ambiguous (undefined days).' },
                    { severity: 'Low', text: 'Governing Law not specified (Defaulting to local jurisdiction).' }
                ],
                summary: 'This is a standard service agreement favorable to the Service Provider. The agreement lacks standard liability caps commonly found in similar industry contracts. The payment terms are clearly defined with NET 30 days clause.',
                missingPoints: [
                    'Force Majeure Clause',
                    'Dispute Resolution Mechanism (Arbitration)',
                    'Intellectual Property Rights Assignment',
                    'Data Privacy and Protection Clause'
                ]
            });
            setReviewSubTab('summary');
        }, 2000);
    };

    const handleAsk = () => {
        if (!chatInput.trim()) return;
        const newMsg = { role: 'user', text: chatInput };
        setChatMessages([...chatMessages, newMsg]);
        setChatInput('');

        setTimeout(() => {
            setChatMessages(prev => [...prev, {
                role: 'ai',
                text: "Based on the agreement, the termination clause requires a 30-day notice period. However, it does not specify penalties for early termination."
            }]);
        }, 1000);
    };

    return (
        <div>
            <input type="file" ref={fileInputRef} style={{ display: 'none' }} accept=".pdf,.docx,.doc,.txt" onChange={handleFileChange} />

            {/* LANDING PAGE */}
            {currentStep === 'landing' && (
                <div style={{ minHeight: '70vh', display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', background: 'linear-gradient(135deg, #1e3a8a 0%, #1e40af 100%)', borderRadius: '16px', padding: '4rem 2rem', textAlign: 'center' }}>
                    <h1 style={{ fontSize: '3.5rem', color: 'white', marginBottom: '1rem', fontWeight: 800 }}>
                        AI-Powered Legal Agreements
                    </h1>
                    <h2 style={{ fontSize: '2.5rem', color: '#fbbf24', marginBottom: '1.5rem', fontWeight: 700 }}>
                        for the Indian Market
                    </h2>
                    <p style={{ fontSize: '1.2rem', color: '#e0f2fe', maxWidth: '700px', marginBottom: '3rem', lineHeight: '1.8' }}>
                        Generate legally compliant contracts, NDAs, and business agreements in minutes. Tailored for Indian laws and regulations.
                    </p>
                    <div style={{ display: 'flex', gap: '1.5rem' }}>
                        <button
                            onClick={() => setCurrentStep('selectType')}
                            className="btn"
                            style={{
                                background: '#fbbf24',
                                color: '#1e3a8a',
                                fontSize: '1.2rem',
                                padding: '1rem 2.5rem',
                                fontWeight: 700,
                                border: 'none',
                                boxShadow: '0 4px 12px rgba(251, 191, 36, 0.4)'
                            }}
                        >
                            <FileText size={20} style={{ marginRight: '0.75rem' }} /> Generate Agreement
                        </button>
                        <button
                            onClick={() => { setCurrentStep('review'); }}
                            className="btn"
                            style={{
                                background: 'transparent',
                                color: 'white',
                                fontSize: '1.2rem',
                                padding: '1rem 2.5rem',
                                fontWeight: 600,
                                border: '2px solid white'
                            }}
                        >
                            View Templates
                        </button>
                    </div>
                </div>
            )}

            {/* SELECT AGREEMENT TYPE */}
            {currentStep === 'selectType' && (
                <div>
                    <button onClick={() => setCurrentStep('landing')} className="btn" style={{ marginBottom: '2rem' }}>
                        ← Back
                    </button>
                    <div style={{ textAlign: 'center', marginBottom: '3rem' }}>
                        <h1 style={{ fontSize: '2.5rem', margin: '0 0 1rem 0', color: '#0f172a' }}>Select Agreement Type</h1>
                        <p style={{ fontSize: '1.1rem', color: '#64748b' }}>Choose from our library of legally vetted templates designed for Indian businesses</p>
                    </div>

                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '1.5rem' }}>
                        {agreementTypes.map((type) => (
                            <div
                                key={type.id}
                                onClick={() => handleTypeSelect(type)}
                                className="paper"
                                style={{
                                    padding: '2rem',
                                    cursor: 'pointer',
                                    transition: 'all 0.3s',
                                    borderTop: '4px solid transparent',
                                    position: 'relative'
                                }}
                                onMouseEnter={(e) => {
                                    e.currentTarget.style.borderTopColor = '#0ea5e9';
                                    e.currentTarget.style.transform = 'translateY(-4px)';
                                    e.currentTarget.style.boxShadow = '0 12px 24px rgba(0,0,0,0.1)';
                                }}
                                onMouseLeave={(e) => {
                                    e.currentTarget.style.borderTopColor = 'transparent';
                                    e.currentTarget.style.transform = 'translateY(0)';
                                    e.currentTarget.style.boxShadow = '0 2px 4px rgba(0,0,0,0.05)';
                                }}
                            >
                                {type.popular && (
                                    <span style={{
                                        position: 'absolute',
                                        top: '1rem',
                                        right: '1rem',
                                        backgroundColor: '#fbbf24',
                                        color: '#1e3a8a',
                                        fontSize: '0.75rem',
                                        fontWeight: 700,
                                        padding: '4px 10px',
                                        borderRadius: '12px',
                                        display: 'flex',
                                        alignItems: 'center'
                                    }}>
                                        <Star size={12} style={{ marginRight: '4px', fill: '#1e3a8a' }} /> Popular
                                    </span>
                                )}
                                <div style={{
                                    width: '60px',
                                    height: '60px',
                                    borderRadius: '12px',
                                    backgroundColor: '#e0f2fe',
                                    display: 'flex',
                                    alignItems: 'center',
                                    justifyContent: 'center',
                                    marginBottom: '1.5rem'
                                }}>
                                    <type.icon size={28} color="#0369a1" />
                                </div>
                                <h3 style={{ fontSize: '1.2rem', margin: '0 0 0.75rem 0', color: '#0f172a', fontWeight: 700 }}>
                                    {type.title}
                                </h3>
                                <p style={{ fontSize: '0.95rem', color: '#64748b', margin: 0, lineHeight: '1.6' }}>
                                    {type.desc}
                                </p>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* FILL FORM */}
            {currentStep === 'fillForm' && selectedType && (
                <div>
                    <button onClick={() => setCurrentStep('selectType')} className="btn" style={{ marginBottom: '2rem' }}>
                        ← Back to Templates
                    </button>

                    <div className="paper" style={{ maxWidth: '900px', margin: '0 auto', padding: '3rem' }}>
                        <div style={{ display: 'flex', alignItems: 'center', marginBottom: '2rem' }}>
                            <div style={{ width: '60px', height: '60px', borderRadius: '12px', backgroundColor: '#fef3c7', display: 'flex', alignItems: 'center', justifyContent: 'center', marginRight: '1.5rem' }}>
                                <selectedType.icon size={28} color="#d97706" />
                            </div>
                            <div>
                                <h2 style={{ fontSize: '1.8rem', margin: 0, color: '#0f172a' }}>{selectedType.title}</h2>
                                <p style={{ margin: '0.25rem 0 0 0', color: '#64748b' }}>{selectedType.desc}</p>
                            </div>
                        </div>

                        {/* Rental Agreement Form */}
                        {selectedType.id === 'rental' && (
                            <div style={{ display: 'grid', gap: '1.5rem' }}>
                                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem' }}>
                                    <div>
                                        <label style={{ display: 'block', fontWeight: 600, marginBottom: '0.5rem', color: '#334155' }}>Landlord Name <span style={{ color: '#ef4444' }}>*</span></label>
                                        <input
                                            type="text"
                                            placeholder="Full legal name"
                                            value={formData.landlordName}
                                            onChange={(e) => setFormData({ ...formData, landlordName: e.target.value })}
                                            style={{ width: '100%', padding: '0.75rem', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '1rem', outline: 'none' }}
                                        />
                                    </div>
                                    <div>
                                        <label style={{ display: 'block', fontWeight: 600, marginBottom: '0.5rem', color: '#334155' }}>Tenant Name <span style={{ color: '#ef4444' }}>*</span></label>
                                        <input
                                            type="text"
                                            placeholder="Full legal name"
                                            value={formData.tenantName}
                                            onChange={(e) => setFormData({ ...formData, tenantName: e.target.value })}
                                            style={{ width: '100%', padding: '0.75rem', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '1rem', outline: 'none' }}
                                        />
                                    </div>
                                </div>
                                <div>
                                    <label style={{ display: 'block', fontWeight: 600, marginBottom: '0.5rem', color: '#334155' }}>Property Address</label>
                                    <textarea
                                        placeholder="Complete address with pin code"
                                        value={formData.propertyAddress}
                                        onChange={(e) => setFormData({ ...formData, propertyAddress: e.target.value })}
                                        style={{ width: '100%', padding: '0.75rem', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '1rem', outline: 'none', minHeight: '100px', fontFamily: 'inherit' }}
                                    />
                                </div>
                                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem' }}>
                                    <div>
                                        <label style={{ display: 'block', fontWeight: 600, marginBottom: '0.5rem', color: '#334155' }}>Monthly Rent (₹)</label>
                                        <input
                                            type="text"
                                            placeholder="e.g., 25000"
                                            value={formData.monthlyRent}
                                            onChange={(e) => setFormData({ ...formData, monthlyRent: e.target.value })}
                                            style={{ width: '100%', padding: '0.75rem', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '1rem', outline: 'none' }}
                                        />
                                    </div>
                                    <div>
                                        <label style={{ display: 'block', fontWeight: 600, marginBottom: '0.5rem', color: '#334155' }}>Security Deposit (₹)</label>
                                        <input
                                            type="text"
                                            placeholder="e.g., 50000"
                                            value={formData.securityDeposit}
                                            onChange={(e) => setFormData({ ...formData, securityDeposit: e.target.value })}
                                            style={{ width: '100%', padding: '0.75rem', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '1rem', outline: 'none' }}
                                        />
                                    </div>
                                </div>
                                <div>
                                    <label style={{ display: 'block', fontWeight: 600, marginBottom: '0.5rem', color: '#334155' }}>State</label>
                                    <select
                                        value={formData.state}
                                        onChange={(e) => setFormData({ ...formData, state: e.target.value })}
                                        style={{ width: '100%', padding: '0.75rem', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '1rem', outline: 'none', backgroundColor: 'white' }}
                                    >
                                        <option value="">Select state</option>
                                        <option value="delhi">Delhi NCR</option>
                                        <option value="maharashtra">Maharashtra</option>
                                        <option value="karnataka">Karnataka</option>
                                        <option value="tamil_nadu">Tamil Nadu</option>
                                        <option value="up">Uttar Pradesh</option>
                                    </select>
                                </div>
                            </div>
                        )}

                        {/* Employment Contract Form */}
                        {selectedType.id === 'employment' && (
                            <div style={{ display: 'grid', gap: '1.5rem' }}>
                                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem' }}>
                                    <div>
                                        <label style={{ display: 'block', fontWeight: 600, marginBottom: '0.5rem', color: '#334155' }}>Employer Name <span style={{ color: '#ef4444' }}>*</span></label>
                                        <input
                                            type="text"
                                            placeholder="Company name"
                                            value={formData.employerName}
                                            onChange={(e) => setFormData({ ...formData, employerName: e.target.value })}
                                            style={{ width: '100%', padding: '0.75rem', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '1rem', outline: 'none' }}
                                        />
                                    </div>
                                    <div>
                                        <label style={{ display: 'block', fontWeight: 600, marginBottom: '0.5rem', color: '#334155' }}>Employee Name <span style={{ color: '#ef4444' }}>*</span></label>
                                        <input
                                            type="text"
                                            placeholder="Full legal name"
                                            value={formData.employeeName}
                                            onChange={(e) => setFormData({ ...formData, employeeName: e.target.value })}
                                            style={{ width: '100%', padding: '0.75rem', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '1rem', outline: 'none' }}
                                        />
                                    </div>
                                </div>
                                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem' }}>
                                    <div>
                                        <label style={{ display: 'block', fontWeight: 600, marginBottom: '0.5rem', color: '#334155' }}>Job Title</label>
                                        <input
                                            type="text"
                                            placeholder="e.g., Software Engineer"
                                            value={formData.jobTitle}
                                            onChange={(e) => setFormData({ ...formData, jobTitle: e.target.value })}
                                            style={{ width: '100%', padding: '0.75rem', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '1rem', outline: 'none' }}
                                        />
                                    </div>
                                    <div>
                                        <label style={{ display: 'block', fontWeight: 600, marginBottom: '0.5rem', color: '#334155' }}>Monthly Salary (₹)</label>
                                        <input
                                            type="text"
                                            placeholder="e.g., 50000"
                                            value={formData.monthlySalary}
                                            onChange={(e) => setFormData({ ...formData, monthlySalary: e.target.value })}
                                            style={{ width: '100%', padding: '0.75rem', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '1rem', outline: 'none' }}
                                        />
                                    </div>
                                </div>
                                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem' }}>
                                    <div>
                                        <label style={{ display: 'block', fontWeight: 600, marginBottom: '0.5rem', color: '#334155' }}>Start Date</label>
                                        <input
                                            type="date"
                                            placeholder="dd-mm-yyyy"
                                            value={formData.startDate}
                                            onChange={(e) => setFormData({ ...formData, startDate: e.target.value })}
                                            style={{ width: '100%', padding: '0.75rem', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '1rem', outline: 'none' }}
                                        />
                                    </div>
                                    <div>
                                        <label style={{ display: 'block', fontWeight: 600, marginBottom: '0.5rem', color: '#334155' }}>Work Location</label>
                                        <select
                                            value={formData.workLocation}
                                            onChange={(e) => setFormData({ ...formData, workLocation: e.target.value })}
                                            style={{ width: '100%', padding: '0.75rem', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '1rem', outline: 'none', backgroundColor: 'white' }}
                                        >
                                            <option value="">Select state</option>
                                            <option value="delhi">Delhi NCR</option>
                                            <option value="bangalore">Bangalore</option>
                                            <option value="mumbai">Mumbai</option>
                                            <option value="chennai">Chennai</option>
                                            <option value="hyderabad">Hyderabad</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        )}

                        {/* Other agreement types can have generic form */}
                        {!['rental', 'employment'].includes(selectedType.id) && (
                            <div style={{ padding: '3rem', textAlign: 'center', color: '#94a3b8' }}>
                                <p>Form fields for {selectedType.title} will be available soon.</p>
                            </div>
                        )}

                        <button onClick={handleGenerateSubmit} className="btn" style={{ marginTop: '2rem', width: '100%', padding: '1rem 2rem', fontSize: '1.1rem', background: '#fbbf24', color: '#1e3a8a', fontWeight: 700, border: 'none', boxShadow: '0 4px 12px rgba(251, 191, 36, 0.3)' }}>
                            ✨ Generate Agreement with AI
                        </button>
                    </div>
                </div>
            )}

            {/* REVIEW TAB (existing code stays the same) */}
            {currentStep === 'review' && (
                <div>
                    <button onClick={() => setCurrentStep('landing')} className="btn" style={{ marginBottom: '2rem' }}>
                        ← Back
                    </button>
                    <p style={{ textAlign: 'center', color: '#64748b', marginBottom: '1.5rem' }}>Upload your agreement or legal document for AI-powered analysis</p>

                    <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '2rem', backgroundColor: '#f8fafc', padding: '0.5rem', borderRadius: '12px', maxWidth: '600px', margin: '0 auto 2rem auto' }}>
                        <button onClick={() => setReviewSubTab('upload')} style={{ flex: 1, background: reviewSubTab === 'upload' ? 'white' : 'transparent', border: 'none', padding: '0.75rem', borderRadius: '8px', cursor: 'pointer', fontWeight: 600, color: reviewSubTab === 'upload' ? 'var(--color-primary)' : '#64748b', transition: 'all 0.2s', boxShadow: reviewSubTab === 'upload' ? '0 2px 4px rgba(0,0,0,0.1)' : 'none' }}>
                            Upload
                        </button>
                        <button onClick={() => setReviewSubTab('summary')} style={{ flex: 1, background: reviewSubTab === 'summary' ? 'white' : 'transparent', border: 'none', padding: '0.75rem', borderRadius: '8px', cursor: 'pointer', fontWeight: 600, color: reviewSubTab === 'summary' ? 'var(--color-primary)' : '#64748b', transition: 'all 0.2s', boxShadow: reviewSubTab === 'summary' ? '0 2px 4px rgba(0,0,0,0.1)' : 'none' }}>
                            Summary
                        </button>
                        <button onClick={() => setReviewSubTab('missing')} style={{ flex: 1, background: reviewSubTab === 'missing' ? 'white' : 'transparent', border: 'none', padding: '0.75rem', borderRadius: '8px', cursor: 'pointer', fontWeight: 600, color: reviewSubTab === 'missing' ? 'var(--color-primary)' : '#64748b', transition: 'all 0.2s', boxShadow: reviewSubTab === 'missing' ? '0 2px 4px rgba(0,0,0,0.1)' : 'none' }}>
                            Missing Points
                        </button>
                        <button onClick={() => setReviewSubTab('qa')} style={{ flex: 1, background: reviewSubTab === 'qa' ? 'white' : 'transparent', border: 'none', padding: '0.75rem', borderRadius: '8px', cursor: 'pointer', fontWeight: 600, color: reviewSubTab === 'qa' ? 'var(--color-primary)' : '#64748b', transition: 'all 0.2s', boxShadow: reviewSubTab === 'qa' ? '0 2px 4px rgba(0,0,0,0.1)' : 'none' }}>
                            Q&A
                        </button>
                    </div>

                    {reviewSubTab === 'upload' && (
                        <div className="paper" style={{ maxWidth: '900px', margin: '0 auto', padding: '3rem', textAlign: 'center' }}>
                            <div
                                onClick={onUploadClick}
                                style={{
                                    border: '2px dashed #cbd5e1',
                                    borderRadius: '16px',
                                    padding: '4rem 2rem',
                                    cursor: 'pointer',
                                    backgroundColor: isScanning ? '#f0f9ff' : '#f8fafc',
                                    transition: 'all 0.3s'
                                }}
                            >
                                {isScanning ? (
                                    <div>
                                        <div style={{ width: '50px', height: '50px', border: '4px solid #e2e8f0', borderTopColor: '#0ea5e9', borderRadius: '50%', animation: 'spin 1s linear infinite', margin: '0 auto 1.5rem auto' }}></div>
                                        <h3 style={{ margin: 0, color: '#0f172a', fontSize: '1.2rem' }}>Analyzing {analysisFile?.name}...</h3>
                                        <p style={{ color: '#0ea5e9', margin: '0.5rem 0 0 0' }}>Extracting clauses & checking risks...</p>
                                    </div>
                                ) : (
                                    <>
                                        <UploadCloud size={64} color="#64748b" style={{ margin: '0 auto 1.5rem auto' }} />
                                        <h3 style={{ margin: 0, fontSize: '1.3rem', color: '#334155' }}>Drop your document here</h3>
                                        <p style={{ color: '#94a3b8', fontSize: '0.95rem', margin: '0.5rem 0 0 0' }}>Supports PDF, DOC, DOCX, TXT files</p>
                                    </>
                                )}
                            </div>
                        </div>
                    )}

                    {reviewSubTab === 'summary' && analysisResult && (
                        <div className="paper fade-in" style={{ maxWidth: '900px', margin: '0 auto', padding: '2rem' }}>
                            <h2 style={{ fontSize: '1.5rem', marginBottom: '1.5rem', display: 'flex', alignItems: 'center' }}>
                                <List size={24} style={{ marginRight: '0.75rem', color: 'var(--color-primary)' }} />
                                Document Summary
                            </h2>
                            <div style={{ backgroundColor: '#f8fafc', padding: '1.5rem', borderRadius: '12px', borderLeft: '4px solid var(--color-primary)' }}>
                                <p style={{ margin: 0, fontSize: '1rem', lineHeight: '1.8', color: '#334155' }}>
                                    {analysisResult.summary}
                                </p>
                            </div>
                        </div>
                    )}

                    {reviewSubTab === 'missing' && analysisResult && (
                        <div className="paper fade-in" style={{ maxWidth: '900px', margin: '0 auto', padding: '2rem' }}>
                            <h2 style={{ fontSize: '1.5rem', marginBottom: '1.5rem', display: 'flex', alignItems: 'center' }}>
                                <AlertTriangle size={24} style={{ marginRight: '0.75rem', color: '#ef4444' }} />
                                Missing Points & Risks
                            </h2>
                            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                                {analysisResult.risks.map((risk, i) => (
                                    <div key={i} style={{ padding: '1.25rem', backgroundColor: '#fef2f2', borderRadius: '12px', borderLeft: '4px solid #ef4444' }}>
                                        <div style={{ display: 'flex', alignItems: 'center', marginBottom: '0.5rem' }}>
                                            <span style={{
                                                padding: '4px 12px', borderRadius: '6px', fontSize: '0.8rem', fontWeight: 600, marginRight: '1rem',
                                                backgroundColor: risk.severity === 'High' ? '#fee2e2' : (risk.severity === 'Medium' ? '#fef3c7' : '#e0f2fe'),
                                                color: risk.severity === 'High' ? '#991b1b' : (risk.severity === 'Medium' ? '#92400e' : '#075985')
                                            }}>
                                                {risk.severity} Risk
                                            </span>
                                        </div>
                                        <p style={{ margin: 0, color: '#7f1d1d', fontSize: '1rem' }}>{risk.text}</p>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {reviewSubTab === 'qa' && analysisResult && (
                        <div className="paper fade-in" style={{ maxWidth: '900px', margin: '0 auto', padding: '2rem', display: 'flex', flexDirection: 'column', minHeight: '500px' }}>
                            <h2 style={{ fontSize: '1.5rem', marginBottom: '1.5rem', display: 'flex', alignItems: 'center' }}>
                                <MessageSquare size={24} style={{ marginRight: '0.75rem', color: 'var(--color-primary)' }} />
                                Ask Questions About This Document
                            </h2>

                            <div style={{ flex: 1, backgroundColor: '#f9f9f9', borderRadius: '12px', padding: '1.5rem', marginBottom: '1.5rem', overflowY: 'auto', maxHeight: '400px' }}>
                                {chatMessages.length === 0 ? (
                                    <div style={{ textAlign: 'center', color: '#94a3b8', padding: '3rem' }}>
                                        <MessageSquare size={48} style={{ margin: '0 auto 1rem auto', opacity: 0.3 }} />
                                        <p style={{ fontSize: '1rem' }}>Ask questions about the agreement</p>
                                    </div>
                                ) : (
                                    chatMessages.map((msg, idx) => (
                                        <div key={idx} style={{ marginBottom: '1rem', textAlign: msg.role === 'user' ? 'right' : 'left' }}>
                                            <div style={{
                                                display: 'inline-block',
                                                padding: '1rem 1.25rem',
                                                borderRadius: '12px',
                                                maxWidth: '80%',
                                                backgroundColor: msg.role === 'user' ? '#0ea5e9' : '#fff',
                                                color: msg.role === 'user' ? '#fff' : '#333',
                                                border: msg.role === 'user' ? 'none' : '1px solid #e2e8f0',
                                                boxShadow: msg.role === 'ai' ? '0 2px 4px rgba(0,0,0,0.05)' : 'none'
                                            }}>
                                                {msg.text}
                                            </div>
                                        </div>
                                    ))
                                )}
                            </div>

                            <div style={{ display: 'flex', gap: '1rem' }}>
                                <input
                                    type="text"
                                    value={chatInput}
                                    onChange={(e) => setChatInput(e.target.value)}
                                    placeholder="Ask a question..."
                                    style={{ flex: 1, padding: '1rem', border: '1px solid #e2e8f0', borderRadius: '12px', fontSize: '1rem', outline: 'none' }}
                                    onKeyPress={(e) => e.key === 'Enter' && handleAsk()}
                                />
                                <button onClick={handleAsk} className="btn btn-primary" style={{ padding: '1rem 2rem' }}>Ask AI</button>
                            </div>
                        </div>
                    )}
                </div>
            )}

            {/* EDITOR TAB - Show generated agreement */}
            {currentStep === 'editor' && (
                <div>
                    <button onClick={() => setCurrentStep('fillForm')} className="btn" style={{ marginBottom: '2rem' }}>
                        ← Back to Edit Form
                    </button>

                    <div className="paper" style={{ padding: '2rem', maxWidth: '900px', margin: '0 auto' }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem', paddingBottom: '1rem', borderBottom: '2px solid #e2e8f0' }}>
                            <div>
                                <h2 style={{ margin: 0, fontSize: '1.5rem', color: '#0f172a' }}>{selectedType?.title || 'Agreement'}</h2>
                                <p style={{ margin: '0.5rem 0 0 0', color: '#64748b' }}>Review and edit your generated agreement</p>
                            </div>
                            <div style={{ display: 'flex', gap: '1rem' }}>
                                <button
                                    onClick={() => {
                                        navigator.clipboard.writeText(generatedContent);
                                        alert('Copied to clipboard!');
                                    }}
                                    className="btn"
                                    style={{ backgroundColor: '#fff', border: '1px solid #e2e8f0' }}
                                >
                                    📋 Copy
                                </button>
                                <button
                                    onClick={() => {
                                        const blob = new Blob([generatedContent], { type: 'text/plain' });
                                        const url = URL.createObjectURL(blob);
                                        const a = document.createElement('a');
                                        a.href = url;
                                        a.download = `${selectedType?.id || 'agreement'}_${new Date().getTime()}.txt`;
                                        a.click();
                                    }}
                                    className="btn btn-primary"
                                >
                                    💾 Download
                                </button>
                            </div>
                        </div>

                        <textarea
                            value={generatedContent}
                            onChange={(e) => setGeneratedContent(e.target.value)}
                            style={{
                                width: '100%',
                                minHeight: '600px',
                                padding: '1.5rem',
                                border: '1px solid #e2e8f0',
                                borderRadius: '8px',
                                fontSize: '0.95rem',
                                fontFamily: 'monospace',
                                lineHeight: '1.8',
                                outline: 'none',
                                resize: 'vertical'
                            }}
                        />

                        <div style={{ marginTop: '2rem', padding: '1rem', backgroundColor: '#fffbeb', borderRadius: '8px', borderLeft: '4px solid #fbbf24' }}>
                            <p style={{ margin: 0, fontSize: '0.9rem', color: '#92400e' }}>
                                💡 <strong>Legal Note:</strong> This document has been generated based on your inputs. Please review carefully and consult with a qualified legal professional before execution. Ensure all placeholders are filled with accurate information.
                            </p>
                        </div>
                    </div>
                </div>
            )}

        </div>
    );
};

export default Agreements;
